### PR TITLE
Added code to Airline Restrictions & Shuffling Parities | Codchef

### PR DESCRIPTION
**Pull request by VishalSehgal525**
The link to the problems is added to the respective readme files.
Please merge the PR and add hacktober fest tag.

### CODE REVIEW

**Comment by anupam-kumar-krishnan** [comment]
Read the steps🙏carefully

**Comment by VishalSehgal525** [comment]
Can you please tell me about which step is violated or what should I refer to?

**Comment by anupam-kumar-krishnan** [comment]
image
Check this out!

**Comment by anupam-kumar-krishnan** [comment]
Thank you for contributing✨

**Pull request merged**
